### ISSUE TITLE
DoS 데모 사이트 수정

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/dos#1]

**Comment by unhochoi** [comment]
1. 화면의 너비를 줄일 경우, 좌측 상단 DoS (Dense or Sparse) 가 한 줄로 표현되도록 글씨 크기 줄이기
2. 화면의 너비를 줄일 경우, 우측 하단 SPMM Method Figure 의 X 축 (Sparse X Sparse, Sparse X Dense) 이 제대로 보여지도록 수정하기
3. 좌측 하단 Submit 항목에서, Matrix info, Input 위에 Help 버튼을 생성한 뒤, Help 버튼 클릭 시, Input 내용이 자동으로 채워지도록 구성
    - Input 은 [Sparse X Sparse] Best Case와 [Sparse X Dense] Best Case가 제공되도록

**Comment by unhochoi** [comment]
현재 채림씨에게 요청드린 상황

**Comment by hyu-leeky** [comment]
진행 사항 체크 필요

**Comment by unhochoi** [comment]
작업 마무리하셔서 반영 완료했습니다.
추가적인 피드백 말씀해주시면 추가적으로 요청하겠습니다.

**Comment by hyu-leeky** [comment]
![image](https://user-images.githubusercontent.com/17699616/170403480-8ee3714c-98eb-493b-a5b9-abe52bbff849.png)

위의 그림처럼 Test Data 부분을 다른 섹션으로 분리하는게 좋을것 같아.

추가될 내용은

Click either "Test Data A" or "Test Data B" to fill in the input matrix dimensions to query. Two sample test data represent cases where different SPMM implementations show performance variation.

위의 내용을 서술 하고 나서 그 아래에
Test Data A , Test Data B 로.

이 내용을 조금 더 잘 보이게 하이라이트 하는 것도 좋을것 같아.
지금처럼 같은 폰트크기로 있으니 눈에 잘 띄지 않는것 같아.

**Comment by hyu-leeky** [comment]
아래에 그래프 보여줄때 X 축에 있는 Sparse X Dense 는 Sparse X Dense (Spark default) 라고 하면 어떨까 싶어. 공간이 될런지는 모르겠네.

**Comment by unhochoi** [comment]
넵, 교수님. 혹시 섹션을 아래 그림처럼 중간정도에 삽입해도 괜찮을까요?


![Image](https://user-images.githubusercontent.com/28581429/170411513-4256a894-a818-455d-8f6c-6927767fe069.png)

**Comment by H0zzae** [comment]
오늘 오전 중에 작업한 뒤 운호님과 수정 완료되면 내일 전에 작업 완료될 것 같습니다.  (~ 6/1)

**Comment by H0zzae** [comment]
오늘 오전 작업 후 수정까지 완료되었습니다. 
https://kmu-dos.github.io/
작업 내용은 아래와 같습니다. 
1.  Test Data A, B 버튼과 입력 부분을 섹션 분리
2. Test Data A, B 버튼에 대한 내용 추가
3. Test Data A, B 버튼이 강조되도록 수정
4. graph label을 "Sparse X Dense" 에서 "Sparse X Dense (Spark default)"로 수정

3번 수정의 경우, 그래프의 width가 작을때, 해당 label이 사선으로 보여지게 됩니다.
줄바꿈을 시도해 보았으나, 적용되지 않았습니다. 그래프가 아래로 내려갈 경우에는 label이 정상적으로 보여집니다.

**Comment by hyu-leeky** [comment]
오케이. 잘 진행되었네요.
4번의 경우 피씨에서 화면 폭을 줄여보니 확인 가능하네요.
이정도는 괜찮을것 같아요. 수고많았어요
